"""Phase 2F Test Suite: Infinite Site Defense (path loops, session IDs, calendar traps, pagination, soft-404 deduplication)."""

import pytest

from app.config import Settings
from app.crawler import CrawlEngine
from app.types import CrawlBudget, CrawlRequest, CrawlStatus
from app.urltools import detect_path_loop, normalize_url
from tests.controlled_crawler_server import ControlledCrawlerServer


@pytest.fixture(scope="module")
def server():
    srv = ControlledCrawlerServer()
    srv.start()
    yield srv
    srv.stop()


def create_engine(tmp_path_factory, executor_mode="serial") -> CrawlEngine:
    data_dir = tmp_path_factory.mktemp(f"crawler_defense_{executor_mode}")
    settings = Settings(
        data_dir=data_dir,
        user_agent="LocalSEOSpider-Test/1.0",
        default_url_cap=50,
        max_url_cap=100,
        default_delay_seconds=0.0,
        request_timeout_seconds=5.0,
        render_timeout_ms=5000,
        max_redirects=4,
        max_document_bytes=2_000_000,
        max_request_retries=1,
        retry_backoff_seconds=0.05,
        max_concurrent_crawls=1,
        render_enabled=False,
        crawl_executor_mode=executor_mode,
        thread_workers=2,
        async_concurrency=2,
        process_workers=2,
        allow_private_crawls=True,
    )
    return CrawlEngine(settings)


def test_detect_path_loop_unit():
    """Verify detect_path_loop detects cyclic directory segment patterns."""
    # 1. Single repeated segment
    assert detect_path_loop("/a/a/a/a", max_repeats=3) is True
    assert detect_path_loop("/a/a", max_repeats=3) is False

    # 2. 2-segment cycle
    assert detect_path_loop("/cat/sub/cat/sub/cat/sub/cat/sub", max_repeats=3) is True
    assert detect_path_loop("/cat/sub/cat/sub", max_repeats=3) is False

    # 3. 3-segment cycle
    assert detect_path_loop("/x/y/z/x/y/z/x/y/z/x/y/z", max_repeats=3) is True

    # 4. Normal deep path without loops
    assert detect_path_loop("/products/electronics/phones/smartphones/accessories", max_repeats=3) is False

    # 5. Full URL input
    assert detect_path_loop("https://example.com/a/b/a/b/a/b/a/b/page", max_repeats=3) is True


def test_session_id_normalization():
    """Verify normalize_url strips Java servlet, ASP.NET, and PHP session identifiers from paths."""
    base = "https://example.com"

    # Java servlet jsessionid
    url1 = "https://example.com/products;jsessionid=ABCD1234EFGH/view"
    assert normalize_url(url1, base) == "https://example.com/products/view"

    # ASP.NET cookieless session
    url2 = "https://example.com/(S(k5n3u2v4y))/default.aspx"
    assert normalize_url(url2, base) == "https://example.com/default.aspx"

    # PHP sid in path
    url3 = "https://example.com/index.php;sid=987654321"
    assert normalize_url(url3, base) == "https://example.com/index.php"


def test_path_loop_trap_defense(server, tmp_path_factory):
    """Verify crawler detects path loops generated by endpoints and skips them."""
    server.reset_counts()
    server.server.robots_status_code = 200
    server.server.robots_content = "User-agent: *\nAllow: /\n"

    engine = create_engine(tmp_path_factory, "serial")
    req = CrawlRequest(
        start_url=f"{server.base_url}/trap/loop/step1/step2/step1/step2/step1/step2/step1/step2",
        mode="site",
        max_urls=10,
        delay_seconds=0.0,
        acknowledgment=True,
    )
    result = engine.run(req, lambda *_: None)

    # The recursive link inside has > 3 repetitions of step1/step2, so frontier skips it
    assert len(result.pages) >= 1
    # Check that skipped links don't run endlessly
    assert len(result.pages) < 10


def test_session_id_trap_deduplication(server, tmp_path_factory):
    """Verify session IDs generated in URLs are stripped so duplicate targets are not re-crawled."""
    server.reset_counts()
    server.server.robots_status_code = 200
    server.server.robots_content = "User-agent: *\nAllow: /\n"

    engine = create_engine(tmp_path_factory, "serial")
    req = CrawlRequest(
        start_url=f"{server.base_url}/trap/session",
        mode="site",
        max_urls=10,
        delay_seconds=0.0,
        acknowledgment=True,
    )
    result = engine.run(req, lambda *_: None)

    # /trap/session yields Java and ASP session links pointing to /trap/session/.../page
    # Normalization strips the session tokens so both normalize to identical clean paths
    urls = [p.url for p in result.pages]
    for u in urls:
        assert ";jsessionid=" not in u
        assert "/(S(" not in u


def test_calendar_trap_bounded_by_budget(server, tmp_path_factory):
    """Verify infinite calendar loops are strictly bounded by crawl budgets."""
    server.reset_counts()
    server.server.robots_status_code = 200
    server.server.robots_content = "User-agent: *\nAllow: /\n"

    engine = create_engine(tmp_path_factory, "serial")
    budget = CrawlBudget(max_pages=4)
    req = CrawlRequest(
        start_url=f"{server.base_url}/trap/calendar/2026/1",
        mode="site",
        max_urls=50,
        delay_seconds=0.0,
        acknowledgment=True,
        budget=budget,
    )
    result = engine.run(req, lambda *_: None)

    assert len(result.pages) == 4
    assert result.status == CrawlStatus.BUDGET_EXHAUSTED.value


def test_infinite_pagination_bounded_by_budget(server, tmp_path_factory):
    """Verify infinite pagination query traps are bounded strictly by crawl budgets."""
    server.reset_counts()
    server.server.robots_status_code = 200
    server.server.robots_content = "User-agent: *\nAllow: /\n"

    engine = create_engine(tmp_path_factory, "serial")
    budget = CrawlBudget(max_pages=3)
    req = CrawlRequest(
        start_url=f"{server.base_url}/trap/pagination?page=1",
        mode="site",
        max_urls=50,
        delay_seconds=0.0,
        acknowledgment=True,
        budget=budget,
    )
    result = engine.run(req, lambda *_: None)

    assert len(result.pages) == 3
    assert result.status == CrawlStatus.BUDGET_EXHAUSTED.value


def test_soft_404_content_deduplication(server, tmp_path_factory):
    """Verify soft-404 error pages returning 200 OK are deduplicated via content hash."""
    server.reset_counts()
    server.server.robots_status_code = 200
    server.server.robots_content = "User-agent: *\nAllow: /\n"

    engine = create_engine(tmp_path_factory, "serial")
    urls = [
        f"{server.base_url}/trap/soft-404/page1",
        f"{server.base_url}/trap/soft-404/page2",
        f"{server.base_url}/trap/soft-404/page3",
    ]
    req = CrawlRequest(
        start_url=urls[0],
        mode="list",
        url_list=urls,
        max_urls=10,
        delay_seconds=0.0,
        acknowledgment=True,
    )
    result = engine.run(req, lambda *_: None)

    # First page is indexed, subsequent identical pages are flagged as content duplicates
    assert len(result.pages) == 3
    duplicates = [p for p in result.pages if p.is_duplicate]
    assert len(duplicates) == 2
